version: '3.1'
services:
  database:
    image: postgres
    container_name: database_entrega
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=hamachi123
      - POSTGRES_DB=entrega

  app:
    build: .
    container_name: entrega
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database