version: '3.8'

services:
  database:
    image: postgres
    container_name: database_entrega
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - pgdata:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 15432:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=
      - PGADMIN_DEFAULT_PASSWORD=
    depends_on:
      - database

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
